In [1]:
import numpy as np

In [2]:
x = np.arange(1, 6)
print(x)

[1 2 3 4 5]


In [5]:
print(f"1st element: {x[0]}")
print(f"2nd element: {x[1]}")
print(f"3rd element: {x[2]}")

1st element: 1
2nd element: 2
3rd element: 3


In [8]:
print(f"1st element: {x[-5]}")
print(f"2nd element: {x[-4]}")
print(f"5th element: {x[-1]}")


1st element: 1
2nd element: 2
5th element: 5


In [9]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [11]:
X = np.arange(1, 10).reshape((3, 3))
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print(f"Element at (0 ,0): {X[0, 0]}")
print(f"Element at (0 ,1): {X[0, 1]}")
print(f"Element at (2 ,2): {X[2, 2]}")

Element at (0 ,0): 1
Element at (0 ,1): 2
Element at (2 ,2): 9


In [14]:
X[0, 0] = 20
print(X)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [16]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [17]:
x = np.delete(x, [0, 4])
print(x)

[2 3 4]


In [18]:
Y = np.arange(1, 10).reshape((3, 3))
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
W = np.delete(Y, 0, axis=0)
print(W)

[[4 5 6]
 [7 8 9]]


In [20]:
V = np.delete(Y, [0, 2], axis=1)
print(V)

[[2]
 [5]
 [8]]


In [25]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, 6)
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]


In [30]:
Y = np.arange(1, 10).reshape((3, 3))
print(Y)

V = np.append(Y, [[10, 11, 12]], axis=0)
print(Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
W = np.append(Y, [[10], [11], [12]], axis=1)
print(W)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [33]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [35]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 3 4 5 6 7]


In [44]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [46]:
W = np.insert(Y, 1, [[4, 5, 6]], axis=0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
V = np.insert(Y, 1, 5, axis=1)
print(V)

[[1 5 2 3]
 [7 5 8 9]]


In [50]:
x = np.array([1, 2])
print(x)
print()
y = np.array([[3, 4], [5, 6]])
print(y)

[1 2]

[[3 4]
 [5 6]]


In [51]:
z = np.vstack((x, y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [53]:
w = np.hstack((y, x.reshape(2, 1)))
print(w)

[[3 4 1]
 [5 6 2]]
