In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]
