In [1]:
import numpy as np

In [2]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
print(X[X > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
print(X[X <= 7])

[0 1 2 3 4 5 6 7]


In [5]:
print(X[(X > 10) & (X < 17)])

[11 12 13 14 15 16]


In [6]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [9]:
x = np.random.randint(1, 11, size=(10, ))

In [12]:
print(np.sort(x))
print(x)

[1 1 1 3 4 4 5 6 8 9]
[4 6 4 3 1 1 9 5 1 8]


In [13]:
print(x.sort())
print(x)

None
[1 1 1 3 4 4 5 6 8 9]


In [17]:
X = np.random.randint(1, 11, size=(5, 5))
print(X)

[[ 2  2  1  4  4]
 [ 6  9  7  7  6]
 [ 2 10  2  8  9]
 [ 4  7  1  2  8]
 [ 5  4  4  8  8]]


In [18]:
print(np.sort(X, axis=0))

[[ 2  2  1  2  4]
 [ 2  4  1  4  6]
 [ 4  7  2  7  8]
 [ 5  9  4  8  8]
 [ 6 10  7  8  9]]


In [19]:
print(np.sort(X, axis=1))

[[ 1  2  2  4  4]
 [ 6  6  7  7  9]
 [ 2  2  8  9 10]
 [ 1  2  4  7  8]
 [ 4  4  5  8  8]]
