In [1]:
import numpy as np

In [4]:
X = np.zeros((3, 4), dtype=int)
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
print("dtype: ", X.dtype)

dtype:  int64


In [7]:
X = np.ones((4, 5))
print(X)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
X = np.full((4, 3), 5)
print(X)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [12]:
X = np.eye(5)
print(X)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
X = np.diag([10, 20, 30, 40])
print(X)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [14]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
x = np.arange(4, 10)
print(x)

[4 5 6 7 8 9]


In [16]:
x = np.arange(1, 20, 3)
print(x)

[ 1  4  7 10 13 16 19]


In [19]:
x = np.linspace(0, 25, 10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [24]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
x1 = np.reshape(x, (4, 5))
print(x1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [27]:
x2 = np.reshape(x, (10, 2))
print(x2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [30]:
x = np.arange(25).reshape((5, 5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [33]:
x = np.random.random((3, 3))
print(x)

[[0.97800842 0.05024599 0.18782482]
 [0.2679968  0.75176682 0.13132709]
 [0.15998627 0.37299547 0.86629768]]


In [34]:
X = np.random.randint(4, 15, size=(3, 2))
print(X)

[[11  8]
 [14 11]
 [10  6]]


In [35]:
X = np.random.normal(0, 0.1, size=(1000, 1000))
print(X)

[[-0.06037434  0.03121098  0.05862819 ...  0.16758142 -0.03193329
  -0.028835  ]
 [ 0.00964386 -0.00687413  0.13311273 ... -0.24832575 -0.00075382
  -0.10034757]
 [ 0.09897507  0.04274753  0.00205414 ...  0.08273483  0.0549755
   0.18591047]
 ...
 [ 0.10084411  0.10918307  0.09543514 ...  0.00998929 -0.00652764
   0.00136987]
 [-0.02252549  0.10602767  0.06099563 ... -0.0512231   0.07657053
  -0.18866283]
 [-0.06728165 -0.01115439  0.10260364 ...  0.00578535 -0.05240454
  -0.03545571]]


In [36]:
print("mean: ", np.mean(X))
print("std: ", np.std(X))
print("min: ", np.min(X))
print("max: ", np.max(X))
print("# positive: ", (X > 0).sum())
print("# negative: ", (X < 0).sum())

mean:  7.435864207789356e-06
std:  0.10001853706512051
min:  -0.4718627208756354
max:  0.49238288529198293
# positive:  500004
# negative:  499996
