In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [4]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
x.dtype

dtype('int64')

In [6]:
x.shape

(5,)

In [9]:
Y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(Y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
Y.shape

(4, 3)

In [13]:
Y.size

12

In [14]:
Y.ndim

2

In [17]:
y = np.zeros((2, 3, 4))
print(y)
y.ndim

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


3

In [18]:
y.dtype

dtype('float64')

In [19]:
x = np.array(['Hello', 'World'])

In [20]:
x.dtype

dtype('<U5')

In [21]:
np.save('my_array', x)