In [1]:
import numpy as np

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [3]:
X = np.arange(1, 21).reshape(4,5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [6]:
z = X[:3, 2:]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [8]:
z = X[:, 2]
print(z)

[ 3  8 13 18]


In [9]:
z = X[:, 2:3]
print(z)

[[ 3]
 [ 8]
 [13]
 [18]]


In [10]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [12]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [15]:
z[2, 2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [14]:
print(X)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [25]:
X = np.arange(0, 20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
z = np.copy(X[1:, 2:])
print(z)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [27]:
z[2, 2] = 555
print(z)

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]


In [28]:
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [30]:
z = X[indices, :]
print(z)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [31]:
z = X[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [32]:
z = np.diag(X)
print(z)

[ 0  6 12 18]


In [33]:
z = np.diag(X, k=1)
print(z)

[ 1  7 13 19]


In [35]:
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [36]:
z = np.unique(X)
print(z)

[1 2 3 5 8]
